import React from 'react';
import Head from 'next/head';

import AppLayout from '@/components/AppLayout';
import CardContentList from '@/components/Lists/CardContentList';
import SectionHeading from '@/components/Common/SectionHeading';
import ProductsList from '@/components/Lists/ProductsList';
import IconContentList from '@/components/Lists/IconContentList';
import PostsList from '@/components/Lists/PostsList';
import HeroCTA from '@/components/Common/HeroCTA';

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';

import { cardContentData, iconContentData, postsData } from '@/assets/data';
import HeroImg from '@/assets/images/hero-img.jpg';
import CustomerReview from '@/components/Common/CustomerReview';

function Home() {
  return (
    <>
      <Head>
        <title>Simple E-Commerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container>
        <Box sx={{ my: '24px' }}>
          <CardContentList data={cardContentData} />
        </Box>
      </Container>

      <Container>
        <SectionHeading
          title='Best Seller Products'
          subTitle={
            <span>
              Problems trying to resolve
              <br />
              the conflict between{' '}
            </span>
          }
        />
        <Box>
          <ProductsList paginate={true} />
        </Box>
      </Container>

      <Container sx={{ mt: '46px' }}>
        <SectionHeading
          topText='Featured Products'
          titleUppercase={true}
          title='The Best Services'
          subTitle={
            <span>
              Problems trying to resolve
              <br />
              the conflict between{' '}
            </span>
          }
        />
        <IconContentList data={iconContentData} />
      </Container>

      <Container sx={{ mt: '46px', mb: '80px' }}>
        <SectionHeading
          title='Featured Posts'
          titleUppercase={true}
          topText='Practice Advice'
          topTextSize='0.875rem'
          topTextColor='primary.main'
          topTextWeight={700}
        />
        <PostsList data={postsData} />
      </Container>

      <Container sx={{ mt: '55px' }}>
        <CustomerReview />
      </Container>

      <HeroCTA
        bgImage={HeroImg.src}
        topText='Designing Better Experience'
        title='Problems trying to resolve the conflict between'
        description='Problems trying to resolve the conflict between the two major realms of Classical physics:'
        highlightText='$16.48'
        ctaText='Add Your Call to Action'
        topTextSize='0.875rem'
        topTextColor='primary.main'
        topTextWeight={700}
      />
    </>
  );
}

Home.getLayout = function getLayout(page: React.ReactNode, pageProps: any) {
  return <AppLayout {...pageProps}>{page}</AppLayout>;
};

export default Home;
